language: python
python: "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -qq python-numpy python-yaml
install:
  - pip install flake8  # Not yet available in Debian stable
  - pip install -r requirements.txt
  # - pip install -e git+https://github.com/openfisca/openfisca-france-data.git#egg=OpenFisca-France-Data  # For test_from_taxipp which is ignored in Makefile
script: make test-ci
