language: python
python: "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-numpy python-pandas python-scipy python-tables
install:
  - pip install isodate  # For Biryani1 datetimeconv
  - pip install -e git+https://github.com/etalab/biryani.git@biryani1#egg=Biryani1  # For OpenFisca-Core
  - pip install -e git+https://github.com/openfisca/openfisca-core.git#egg=OpenFisca-Core
  - pip install xlrd  # For IPP tests
  - pip install -r requirements.txt
script: nosetests openfisca_france/tests
