sudo: false # Use new Travis container-based infrastructure
language: python
python: 2.7
cache: pip
install:
  - pip install --upgrade pip  # pip >= 8.0 needed to be compatible with "manylinux" wheels, used by numpy >= 1.11
  - pip install flake8
  - pip install --editable .[test]
script: bash run-travis-tests.sh
before_deploy:
- python setup.py compile_catalog
- openssl aes-256-cbc -K $encrypted_5636fd88352f_key -iv $encrypted_5636fd88352f_iv
  -in openfisca_bot.enc -out openfisca_bot -d
deploy:
  - provider: script
    skip_cleanup: true
    script: ./release-tag.sh
    on:
      branch: master
  - provider: pypi
    user: openfisca-bot
    password:
      secure: MeMIzLAYH2AkilY2/acUHrlC4jycLLNbUzmQAATthDfs1zcoZuHt6qEkQ1E1bPNjAP/0RE9iKFsk8ivgh7fpyNiqwc928se0SHj1wQn7n/Brf5F7eNHTgABRC/80TgB/6zVdyy9VkL4DjF2mJXr/pLOTAS+myOqcuToJ6wMLXkM=
    distributions: "bdist_wheel"
    on:
      tags: true
